name: Dataset Pull Automation

on:
  workflow_dispatch

jobs:
  Pull_datasets:
    runs-on: ubuntu-latest
    env: 
      jkanPath: jkan
      odbodsPath: the_od_bods
      
    steps:
    # Init repos
    - name: Check out OD bods toolset repo
      uses: actions/checkout@v3
      with: 
        repository: 'OpenDataScotland/the_od_bods'
        path: 'the_od_bods'
    - name: Check out JKAN repo
      uses: actions/checkout@v3
      with: 
        repository: 'OpenDataScotland/jkan'
        path: 'jkan'
    - name: Check files
      run: ls -l -a


   # Set up programming toolsets
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
          python-version: '3.9'
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    # ArcGIS portals
    - name: Run Script arcgis.py
      run: python arcgis.py
      working-directory: ${{env.odbodsPath}}

    # USMART portals
    - name: Run Script py_USMART_import/Import_DCAT.ipynb
      run: python ./Import_DCAT.ipynb
      working-directory: ${{env.odbodsPath}}/py_USMART_import

    # CKAN portals
    - name: Restore dependencies
      run: dotnet restore ${{env.odbodsPath}}/CKANOpenDataImport/CKANOpenDataImport.csproj
    - name: Build
      run: dotnet build ${{env.odbodsPath}}/CKANOpenDataImport/CKANOpenDataImport.csproj --no-restore
    - name: Run
      working-directory: ${{env.odbodsPath}}/CKANOpenDataImport
      run: dotnet run
    - name: Copy output to folder
      run: cp ${{env.odbodsPath}}/CKANOpenDataImport/ckan_output.csv ${{env.odbodsPath}}/data/ckan_output.csv

    # DCAT feeds
    - name: Run Script dcat.py
      run: python ./dcat.py
      working-directory: ${{env.odbodsPath}}

    # Merge data
    - name: Install dependencies for merge_data.py
      run: python -m pip install pandas markdown pyyaml
    - name: Run Script merge_data.py
      run: python ./merge_data.py
      working-directory: ${{env.odbodsPath}}

    # Convert merged CSV to Markdown files 
    - name: Run Script export2jkan.py
      run: python ./export2jkan.py
      working-directory: ${{env.odbodsPath}}

    # Commit changes
    # - name: Git config
    #   working-directory: ${{env.jkanPath}}
    #   run: |
    #     git config user.name "GitHub Actions"
    #     git config user.email "<>"
    - name: Git status
      run: git status
      working-directory: ${{env.jkanPath}}
    # - name: Commit and push
    #   run: git add -A && git commit -m "Dataset Sync" && git push origin gh-pages
    #   working-directory: ${{env.jkanPath}}
    - name: Pushes to JKAN
      uses: cpina/github-action-push-to-another-repository@main      
      env:
        API_TOKEN_GITHUB: ${{ secrets.REPO_COMMIT_TOKEN }}
      with:
        source-directory: ${{env.jkanPath}}
        destination-repository-username: 'OpenDataScotland'
        destination-repository-name: 'jkan'
        target-branch: 'gh-pages'
        user-name: 'GitHub Actions'
        user-email: <>

