name: Dataset Pull Automation

on:
  workflow_dispatch:

  schedule:
    - cron: '0 12 * * FRI'

jobs:
  Pull_datasets:
    runs-on: ubuntu-latest
    env: 
      jkanPath: jkan
      odbodsPath: the_od_bods
      
    steps:
    # Init repos
    - name: Check out OD bods toolset repo
      uses: actions/checkout@v3
      with: 
        repository: 'OpenDataScotland/the_od_bods'
        path: 'the_od_bods'
    - name: Check out JKAN repo
      uses: actions/checkout@v3
      with: 
        repository: 'OpenDataScotland/jkan'
        path: 'jkan'
        token: ${{ secrets.REPO_COMMIT_TOKEN }}
    - name: Check files
      run: ls -l -a


   # Set up programming toolsets
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
          python-version: '3.9'
    - name: Install dependencies for python scripts
      run: python -m pip install pandas markdown pyyaml beautifulsoup4 datefinder requests
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    # ArcGIS portals
    - name: Run Script arcgis.py
      run: python arcgis.py
      working-directory: ${{env.odbodsPath}}

    # USMART portals
    - name: Run Script usmart.py
      run: python ./usmart.py
      working-directory: ${{env.odbodsPath}}

    # CKAN portals
    - name: Restore dependencies
      run: dotnet restore ${{env.odbodsPath}}/CKANOpenDataImport/CKANOpenDataImport.csproj
    - name: Build
      run: dotnet build ${{env.odbodsPath}}/CKANOpenDataImport/CKANOpenDataImport.csproj --no-restore
    - name: Run
      working-directory: ${{env.odbodsPath}}/CKANOpenDataImport
      run: dotnet run
    - name: Copy output to folder
      run: cp ${{env.odbodsPath}}/CKANOpenDataImport/ckan_output.csv ${{env.odbodsPath}}/data/ckan_output.csv

    # DCAT feeds
    - name: Run Script dcat.py
      run: python ./dcat.py
      working-directory: ${{env.odbodsPath}}
      
    # aberdeenshire_council_scraper feeds
    - name: Run Script aberdeenshire_council_scraper.py
      run: python ./aberdeenshire_council_scraper.py
      working-directory: ${{env.odbodsPath}}/web-scrapers
      
    # east_ayrshire_scraper feeds
    - name: Run Script east_ayrshire_scraper.py
      run: python ./east_ayrshire_scraper.py
      working-directory: ${{env.odbodsPath}}/web-scrapers
      
    # moray_council_scraper feeds
    - name: Run Script moray_council_scraper.py
      run: python ./moray_council_scraper.py
      working-directory: ${{env.odbodsPath}}/web-scrapers

    # Merge data
    - name: Run Script merge_data.py
      run: python ./merge_data.py
      working-directory: ${{env.odbodsPath}}

    # Convert merged CSV to Markdown files 
    - name: Run Script export2jkan.py
      run: python ./export2jkan.py
      working-directory: ${{env.odbodsPath}}

    # Commit changes
    - name: Git config
      working-directory: ${{env.jkanPath}}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "<>"
    - name: Git status
      run: git status
      working-directory: ${{env.jkanPath}}
    - name: Commit and push
      run: git add -A && git commit -m "Dataset Sync" && git push origin gh-pages
      working-directory: ${{env.jkanPath}}

    # Tell the Slack channel!
    - name: Slack Notification
      working-directory: ${{env.jkanPath}}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      run: | 
        COMMIT=$(git rev-parse HEAD)
        curl --location --request POST ''$SLACK_WEBHOOK'' \
        --header 'Content-Type: application/json' \
        --data-raw '{"text": "I just did a sync!\nCheck out the commit information here: https://github.com/OpenDataScotland/jkan/commit/'$COMMIT'",
        "icon_url":"https://opendata.scot/img/ods_logo.png",
        "username":"ODS sync bot"
        }'
          
